static: "static"

routes:
    - url: "/"
      handler: "About->index"
    - url: "/reg"
      handler: "Login->registration"
    - url: "/login"
      handler: "Login->login"
    - url: "/logout"
      handler: "Login->logout"
    - url: "/@{text}"
      handler: "User->view"
    - url: "/settings"
      handler: "User->settings"
    - url: "/api/{text}.{text}"
      handler: "API->route"
    - url: "/token"
      handler: "API->tokenLogin"